# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        projects: ["Project_A", "Project_B", "Project_C"]
    runs-on: windows-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, ${{matrix.projects}}!
      #with:
      #  project: ${{ matrix.projects }}

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
