# This is a basic workflow to help you get started with Actions

name: IICS CLI Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "export"
  IICS_CLI_Steps:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Test Echo with input
        run: echo "${{ github.event.inputs.message }} ${{ github.event.inputs.name }}"
      # Runs a single command using the runners shell
      - name: List Artifacts
        run: iics_cli/iics.exe list -u ${{ secrets.IICS_USER}} -p ${{ secrets.IICS_PW}} -r em -q "location==Test"
      - name: Export Artifacts
        run: iics_cli/iics.exe export -u ${{ secrets.IICS_USER}} -p ${{ secrets.IICS_PW}} -r em -n export_test -a Test.PROJECT -z zipfile.zip
